adding Trivvy report

diff --git a/.github/workflows/build-scan-push.yml b/.github/workflows/build-scan-push.yml
--- a/.github/workflows/build-scan-push.yml
+++ b/.github/workflows/build-scan-push.yml
@@ -53,14 +53,47 @@ jobs:
           docker images
 
       - name: run anchore grype scan
-        id: scan
+        id: grype-scan
         if: ${{ matrix.target == 'production' }}
-        uses: anchore/scan-action@v3
+        uses: anchore/scan-action@v6
         with:
           image: ${{steps.setImageDetails.outputs.fullImageName}}
           fail-build: false
           severity-cutoff: "medium"
-          output-format: "sarif"
+        continue-on-error: true
+
+      - name: Run Aqua Trivy scan
+        id: trivy-scan
+        if: ${{ matrix.target == 'production' }}
+        uses: aquasecurity/trivy-action@0.30.0
+        with:
+          image-ref: ${{steps.setImageDetails.outputs.fullImageName}}
+          format: sarif
+          output: trivy-reports-node-${{ matrix.image.nodeVersion }}
+          exit-code: 1
+          vuln-type: os,library
+          severity: CRITICAL,HIGH,MEDIUM
+        continue-on-error: true
+
+      - name: Upload Grype SARIF report
+        if: ${{ steps.grype-scan.outcome == 'failure' && matrix.target == 'production' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: grype-reports-node-${{ matrix.image.nodeVersion }}
+          path: ${{ steps.grype-scan.outputs.sarif }}
+
+      - name: Upload Trivy SARIF report
+        if: ${{ steps.trivy-scan.outcome == 'failure' && matrix.target == 'production' }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-reports-node-${{ matrix.image.nodeVersion }}
+          path: trivy-reports-node-${{ matrix.image.nodeVersion }}
+
+      - name: Fail build if scans failed
+        if: ${{ (steps.grype-scan.outcome == 'failure' || steps.trivy-scan.outcome == 'failure') && matrix.target == 'production' }}
+        run: |
+          echo "One or more scans failed. Failing the build."
+          exit 1
 
       - name: Tag image
         run: |
@@ -88,12 +121,6 @@ jobs:
           do
             docker image push ${{steps.setImageDetails.outputs.dockerRepoName}}:$TAG
           done
-
-      - name: Upload Anchore Grype SARIF report
-        if: always() && steps.scan.outputs.sarif
-        uses: github/codeql-action/upload-sarif@v3
-        with:
-          sarif_file: ${{ steps.scan.outputs.sarif }}
 
       - name: Inspect action SARIF report
         if: always() && steps.scan.outputs.sarif
